travis:
  secure:
    BINSTAR_TOKEN: iAf1FArImO4QBrxylQ+5qqM79SHeUepixuRFze09gUEn8rxRf6hOkRbt8bK0pP6icbIRz1uGvhfvQEnRHaTk6iyF8VxBS1aD9L1aqll3gnpHOr1smjVjUNX2tdV1jC3a8YRjYdvo/MuJPFKcdL24H/NLjm9UZAv8byjURcu2T/nCdO2ocJuNOWspJdyyEXoEdHXtt6whahFG3NKpxR/fFtxqxqvgyGQeCBZvli7FEcOmnmdUIUWMWUiS3VI8+6MUCxLnVS2GX3MQooYfAiNvohHZB8z7VJVqdolQrk+uscYlccBicG1mTVqlWuj2ao+IuWcy+ywmrW04HEK7EJrtSGoHH77h8aGqfQe1NG7PjzLmwbtCa1AeVEeYHUiiSPvzHt/aKR5larn+uh/vmnIylNiMH+7Hf/zx7oM4nw95+cXPKa1IUbEC4dJptRT4hsUkFm2GeEWtJViKtk+r1oFJ21Yl3qQyGM2mRcTxBBp5GNgfqCFs+EvZDCf5kYVLkVtQkuwogQXx7tp90HcnRLIC1QxPoCk2RXfHeuat4GmX7VV+gxHeY37t5dQcvg48ynsl/jGwUq8dhgJXwlfDKVFTbuSCVj5C3jF/3FXN1X1zMdYra8la2VzUBLRwhX1pOFX4QNaw7Dzg5wE3UlNYRROdgfqFqzgX82IlOSy07pKa21Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
